parameters:
  repertoire_illustrations: '%kernel.project_dir%/public/images/courses'
  repertoire_videos: '%kernel.project_dir%/public/videos'
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
